@token = {{login.response.body.data.access_token}}
@id= 4e53ec4e-b067-4964-9a7e-8720081bb1e7

###
# @name login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "username": "mentor1",
  "password": "123456"
}

###
# @name create-task
POST http://localhost:3000/tasks
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Task1-1"
}

###
# @name get-all-tasks
GET http://localhost:3000/tasks
Authorization: Bearer {{token}}
Content-Type: application/json

###
# @name get-task-by-id
GET http://localhost:3000/tasks/{{id}}
Authorization: Bearer {{token}}
Content-Type: application/json


###
# @name update-task
PUT http://localhost:3000/tasks/{{id}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Task1-1"
}

